mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
server:
  port: 8090
  ssl:
    key-store: classpath:blog-yoghurts-cn.pfx
    key-store-password: IDDX6zAE
    key-store-type: PKCS12
    enabled: false

yoghurt:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800 # 7 days
    header: Authorization

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: root

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379



